new/feed/urls.py
from django.conf.urls import url
from . import views


app_name = 'feed'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
   #url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='read'),
	url(r'^(?P<pk>[0-9]+)/$', views.story_detail, name='read'),
	url(r'^(?P<pk>[0-9]+)/like/$', views.story_like, name='like'),
	url(r'publish/$', views.AddStory.as_view(), name='story-publish'),
	url(r'^(?P<pk>[0-9]+)/edit/$', views.StoryUpdate.as_view(), name='story-edit'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.StoryDelete.as_view(), name='story-delete'),
	#comment
    #url(r'^(?P<pk>[0-9]+)/$', views.comment, name='comment'),


	url(r'^about/$', views.about, name='about'),
	url(r'^profile/$', views.profile, name='profile'),

]


new/story/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^feed/', include('feed.urls')),
   	url(r'^admin/', admin.site.urls),

]    

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

new/feed/models.py
from django.db import models
from datetime import date
from django.utils.translation import gettext as _
from django.core.urlresolvers import reverse


class story(models.Model):
	author = models.CharField(max_length=250)
	story_title = models.CharField(max_length=250)
	date = models.DateField(_("Date"), default=date.today)
	genre = models.CharField(max_length=100)
	story_logo = models.FileField()
	content = models.TextField(max_length=15000)
	likes = models.PositiveIntegerField(default=0)
	
	def get_absolute_url(self):
		return reverse('feed:read', kwargs={'pk': self.pk}) 


	def __str__(self):
		return self.story_title

class comment(models.Model):
	story = models.ForeignKey(story, related_name='comments')
	name = models.CharField(max_length=80)
	email = models.EmailField()
	body = models.TextField()
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	active = models.BooleanField(default=True)

	class Meta:
		ordering = ('created',)

	def __str__(self):
		return 'Comment by {} on {}'.format(self.name,self.story)

new/feed/forms.py
from django import forms
from .models import comment


class CommentForm(forms.ModelForm):
	class Meta:
		model = comment
		fields = ('name','email','body')

new/feed/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.core.urlresolvers import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import story, comment
from .forms import CommentForm


class IndexView(generic.ListView):
	template_name = 'feed/index.html'
	context_object_name = 'all_stories'


	def get_queryset(self):
		return story.objects.all()

'''class DetailView(generic.DetailView):
	model = story
	template_name = 'feed/detail.html'
'''

def story_detail(request, pk):
	story_obj = get_object_or_404(story, pk=pk)
	#list of active comments for story
	comments = story_obj.comments.filter(active=True)

	if request.method == 'POST':
		# if a comment was posted
		comment_form = CommentForm(data=request.POST)
		if comment_form.is_valid():
			#create comment object but don't save to DB yet
			new_comment = comment_form.save(commit=False)
			#Assign the current story to comment
			new_comment.story = story_obj
			#save the comment to DB
			new_comment.save()
	else:
		comment_form = CommentForm()
	return render(request, 'feed/detail.html', {'story': story_obj, 'comments': comments, 'comment_form': comment_form})

'''def comment(request):
	#list of active comments for story
	comments = story.comments.filter(active=True)

	if request.method == 'POST':
		# if a comment was posted
		comment_form = CommentForm(data=request.POST)
		if comment_form.is_valid():
			#create comment object but don't save to DB yet
			new_comment.story = story
			#save the comment to DB
			new_comment.save()
	else:
		comment_form = CommentForm()
	return render(request, 'feed/detail.html', {'comments':comments,'comment_form':comment_form})
'''


class AddStory(CreateView):
	model = story
	fields = ['author', 'story_title', 'genre', 'content', 'story_logo']

class StoryUpdate(UpdateView):
	model = story
	fields = ['author', 'story_title', 'genre', 'content', 'story_logo']

class StoryDelete(DeleteView):
	model = story
	success_url = reverse_lazy('feed:index')



def about(request):
	return render(request, 'feed/about.html')


def profile(request):
	return render(request, 'feed/profile.html')


def story_like(request, pk):
	story_obj = get_object_or_404(story, pk=pk)
	story_obj.likes += 1
	story_obj.save()
	context = story.objects.all()
	return render(request, 'feed/index.html', {'all_stories': context})


'''def publish(request):
	if request.method == 'POST':
		form = PublishForm(request.POST,request.FILES)
		if form.is_valid():
			author = form.cleaned_data['author']
			story_title = form.cleaned_data['story_title']
			genre = form.cleaned_data['genre']
			content = form.cleaned_data['content']
			story_logo = request.FILES['story_logo']
			obj = story()
			obj.author = author
			obj.story_title = story_title
			obj.genre = genre
			obj.content = content
			obj.story_logo = story_logo
			obj.save()
			all_stories = story.objects.all()
			context = {'all_stories': all_stories}
			return render(request, 'feed/index.html', context)

	else:
		form = PublishForm()
	return render(request,'feed/publish.html',{'form': form})
'''

new/feed/templates/feed/about.html
{% extends 'feed/base.html' %}
		{% block body %}	

		<section>
			<h3 class="center">This is about us</h3>


		</section>
		
	
		{% endblock %}

new/feed/templates/feed/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Title</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		{% load staticfiles %}
		<link rel="stylesheet" type="text/css" href="{% static 'feed/css/bootstrap.min.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'feed/css/bootstrap-theme.min.css' %}">
		<script src="https://use.fontawesome.com/baa68ae363.js"></script>
		<link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet">
		<script src="{% static 'feed/js/jquery-3.1.1.slim.js' %}"></script>
		<script src="{% static 'feed/js/bootstrap.js' %}"></script>
		<link rel="stylesheet" type="text/css" href="{% static 'feed/css/style.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'feed/css/form.css' %}">

	</head>
	<body class="background" background="{% static 'feed/images/new.jpg' %}">
		<nav class="navbar fixed-nav-bar navbar-default">
			<div class="container-fluid">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mainNavBar">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<!--logo-->
					<a href="{% url 'feed:index' %}" class="navbar-brand">Title</a>
				</div>
				<div class="collapse navbar-collapse" id="mainNavBar">
					<ul class="nav navbar-nav">
						<form class="navbar-form navbar-left">
							<input class="form-control form-search" role="search" autocomplete="off" name="q" action="#" placeholder="What would you like to read..." />
							<button class="btn search" type="search">Search</button>
						</form>


						
						<li class="nav-contents"><a href="{% url 'feed:story-publish' %}">Publish</a></li>

					</ul>

					<ul class="nav navbar-nav navbar-right">
						<li>
							<div class="nav pull-right">
								<button type="button" class="login" data-toggle="modal" data-target="#popUp">Log In</button>
								<div class="modal fade" id="popUp">
									<div class="modal-dialog">
										<div class="modal-content">
											<div class="modal-header">
												<button type="button" class="close" data-dismiss="modal">&times;</button>
												<h3 class="modal-title center">Log In</h3>
										<div class="modal-body">
													<form role="form">
														<div class="input-group">
														   <span class="input-group-addon"><i class="fa fa-envelope-o fa-fw"></i></span>
															<input type="email" class="form-control" placeholder="E-mail">
														</div>
														<div class="input-group">
															<span class="input-group-addon"><i class="fa fa-key fa-fw"></i></span>
															<input type="password" class="form-control" placeholder="Password">
														</div>
														<div class="modal-footer">
															<button class="btn btn-primary btn-block">Log In</button>
															<a href="forgot-password" class="center">Forgot Password</a>
														</div>
													</form>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</li>
					</ul>
				</div>
				
			</div>
		</nav>
	
	{% block body %}
	{% endblock %}

	
	
	</body>
	<footer class="footer"> 
			<div class="footer-container">
				<p>Made with <i class="fa fa-heart-o" aria-hidden="true"></i> in India</p>

				
			</div>
	</footer>
</html>

new/feed/templates/feed/comments.html
{% extends 'feed/detail.html' %}
{% block comment %}
{% with comments.count as total_comments %}
<h2>{{ total_comments }} comment {{total_comments|pluralize}}</h2>
{% endwith %}

{% for comment in comments %}
	<div class="comment">
		<p class="info">
			Comment {{ forloop.counter }} by {{comment.name }}
			{{ comment.created }}
		</p>
		{{ comment.body|linebreaks }}
	</div>
	{% empty %} 
	<p>There are no comments yet.</p>
{% endfor %}

	{% if new_comment %}
		<h2>Your comment has been added.</h2>
	{% else %}
		<h2>Add a new comment</h2>
		<form action="." method="post">
			{{ comment_form.as_p }}
			{% csrf_token %}
			<p><input type="submit" value="Add comment"></p>
		</form>


	{% endif %}

{% endblock %}

new/feed/templates/feed/detail.html
{% extends 'feed/base.html' %}
	
		{% block body %}
	<div class="container">
	<section>
	  <div class="col-lg-12">
		<div class="main-container">
			<div class="row">
			    <div class="col-sm-3 img-section">
                    <div class="center">
                        <img class="story-pic" src="{{ story.story_logo.url }}" />
                        <h5><br/> <b>{{ story.author }}</b> </h5>
                        <h6>{{ story.date }}</h6>
                    </div>
                </div>
				<div class="col-sm-9 writing-section">
					<h2 class="story_title"><b>{{ story.story_title }}<br><br></b></h2>
					<p class="story_content">{{ story.content|linebreaks }}</p>
                <!--commenting-->
                  
                <!--till here-->
                    <div class="stack">
                      <button class="btn-danger btn btn-padding" data-toggle="modal" data-target="#confirm-delete">
                        Delete
                      </button>
                      <form action="{% url 'feed:story-edit' story.id %}" method="get">
                        {% csrf_token %}
                    <button class="btn btn-primary btn-padding">Edit</button>
                      </form>
                      <form action="{% url 'feed:like' story.id %}" method="get">
                      <button class="btn btn-block btn-primary"><i class="fa fa-thumbs-up"> Like ({{ story.likes }})</i> </button>
                      </form>
                    </div>

                    <div class="modal fade" id="confirm-delete">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                </div>
                                <div class="modal-body">
                                    <h3>Are you sure?</h3>
                                </div>
                                <div class="modal-footer">
                                     <form action="{% url 'feed:story-delete' story.id %}" method="post">
                                        {% csrf_token %}
                                        <button class="btn btn-danger">Delete</button>
                                        <button class="btn-primary btn" data-dismiss="modal">No</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    
 {% with comments.count as total_comments %}
<h2>{{ total_comments }} comment{{total_comments|pluralize }}</h2>
{% endwith %}

{% for comment in comments %}
    <div class="comment">
        <p class="info">
            Comment {{ forloop.counter }} : {{comment.name }} |
            {{ comment.created }}
        </p>
        {{ comment.body|linebreaks }}
    </div>
    {% empty %} 
    <p>There are no comments yet.</p>
    
    {% endfor %}
    {% if new_comment %}
        <h2>Your comment has been added.</h2>
    {% else %}
        <h2>Add a new comment</h2>
        <form action="." method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Add comment"></p>
        </form>


    {% endif %} 

                     
                </div>


			</div>
		</div>
	</section>
	</div>		
				
		{% endblock %}

new/feed/templates/feed/form-template.html
<!--

<div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
		<span class="text-danger small">{{ field.errors }}</span>
	</div>
	<label class="control-label col-sm-2">{{ field.label_tag }}</label>
	<div class="col-sm-10 field">{{ field }}</div>
</div>

dfor %}-->


	{% for field in form %}
	<fieldset>
		<div class="form-group">
			
				<span class="text-danger small">{{ field.errors }}</span>
			
			<label class="control-label label-font">{{ field.label_tag }}</label>
			<div class="field">{{ field }}</div>
		</div>
		</fieldset>
{% endfor %}

new/feed/templates/feed/index.html
{% extends 'feed/base.html' %}
{% block body %}
		<div class="container">
			<div class="row">
		{% for story in all_stories reversed %}
				<div class="col-md-4 col-sm-5 col-xs-10 content">
					<div class="hovereffect">
						<img class="img-responsive logo" src="{{ story.story_logo.url }}" alt="">
						<div class="overlay">
							<h2>{{ story.story_title }}</h2>
							<h4>{{ story.genre }}</h4>
							<a class="info" href="{% url 'feed:read' story.id %}">Read</a>

						</div>
				   <p>&nbsp;&nbsp;&nbsp;</p>
				    </div>
				</div>
    	{% endfor %}
			</div>
		</div>


{% endblock %}

new/feed/templates/feed/profile.html
{% extends 'feed/base.html' %}
		{% block body %}	
	
		<section>
			<div class="col-md-3">
				<div class="profile-left">
					<h2 class="profile-text">Prafful Kumar</h2>
				
					<div class="profile-pic">
						<img src="Cupslice-14052015083649.jpg" class="img-circle" width=210px height=210px>
					</div>
				</div>
			</div>
		
		
		</section>
		
		{% endblock %}

new/feed/templates/feed/story_form.html
{% extends 'feed/base.html' %}
{% block body %}
<div class="form-style">
	<form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
		{% csrf_token %}
        <h1 class="center">Create your stories...</h1>
		{% include 'feed/form-template.html' %}
		<div class="form-group">
        <button type="submit" class="btn-block">Submit</button>
	    </div>

    </form>
</div>

{% endblock %}	